In [2]:
print("Hello world")

Hello world


# NumPy


In [3]:
import numpy as np

In [8]:
arr = np.array([20,15,21,36])
arr

array([20, 15, 21, 36])

###### Dimension is dependent on bracket in array function 

In [7]:
arr = np.array([[[20,15,21,36]]])
arr.ndim

3

Differnt array Creating


In [10]:
arr = np.ones(4)
arr


array([1., 1., 1., 1.])

In [14]:
arr = np.ones([4,5])
arr


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
arr = np.zeros(4)
arr


array([0., 0., 0., 0.])

In [13]:
arr = np.identity(4)
arr


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
arr = np.array([6,65423,45,32,4521,2,4521,545,12,465,13,43,354,2])

print(np.sort(arr))


[    2     2     6    12    13    32    43    45   354   465   545  4521
  4521 65423]


In [34]:
arr[3:]

array([  32, 4521,    2, 4521,  545,   12,  465,   13,   43,  354,    2])

In [35]:
arr[:-2]

array([    6, 65423,    45,    32,  4521,     2,  4521,   545,    12,
         465,    13,    43])

In [37]:
arr[::-1]

array([    2,   354,    43,    13,   465,    12,   545,  4521,     2,
        4521,    32,    45, 65423,     6])

In [38]:
arr[::5]

array([ 6,  2, 13])

In [58]:
ar = np.arange(start=1,stop=25,step=1).reshape(6,4)
ar

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [62]:
ar[2:4,1:3]

array([[10, 11],
       [14, 15]])

In [66]:
a1 = np.array([12,15.5,15+1j,"he"])
a1

array(['12', '15.5', '(15+1j)', 'he'], dtype='<U64')

# Pandas


In [68]:
import pandas as pd

In [69]:
s1 = pd.Series([12,12.4,21+2j,"hello"])
s1

0         12
1       12.4
2    (21+2j)
3      hello
dtype: object

In [71]:
s1 = pd.Series([12,12.4,21+2j,"hello"])
s1.ndim

1

In [77]:
In [5]: dates = pd.date_range("20130101", periods=6)

df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
df

A         B         C         D
2013-01-01  0.477872  0.874072  0.769542  1.557653
2013-01-02  0.017855 -0.608879 -0.144942  0.965666
2013-01-03 -1.368359  0.716388  0.102146 -1.164404
2013-01-04  0.402679  0.210486  0.656268  1.462520
2013-01-05  1.619420  0.637718  0.795359  0.120655
2013-01-06  0.957912 -1.142250 -0.506621 -0.757954

In [80]:
s1 = pd.Series([12,32,42,2.53,34.2],index=["a","d","f","e","r"])
s1

a    12.00
d    32.00
f    42.00
e     2.53
r    34.20
dtype: float64

In [96]:
a1 = list([1,2,3,4])
pq = pd.DataFrame(a1)
pq

0
0  1
1  2
2  3
3  4

In [109]:
a2 = { "a":1, "b":2, "c":3 }
pq = pd.DataFrame(a2,index=[0])
pq

a  b  c
0  1  2  3

In [102]:
a1 = np.array([12,15.5,15+1j,"he"])
pq = pd.DataFrame(a1)
pq*

0
0       12
1     15.5
2  (15+1j)
3       he

In [104]:
s1 = pd.Series([12,12.4,21+2j,"hello"])
pq = pd.DataFrame(s1)
pq

0
0       12
1     12.4
2  (21+2j)
3    hello

In [137]:
kl = {"a":[12,15],"b":[15,17],"C":[18,16]}
sj = pd.DataFrame(kl)
sj

a   b   C
0  12  15  18
1  15  17  16

In [138]:
del sj["C"]

In [139]:
sj

a   b
0  12  15
1  15  17

In [140]:
sj["c"] = [12,45]
sj

a   b   c
0  12  15  12
1  15  17  45

In [142]:
sj["b"][1] = 15

In [143]:
sj

a   b   c
0  12  15  12
1  15  15  45

In [148]:
df = pd.read_csv(r"C:\Users\computer\Desktop\ANI\CrashCourse\heart.csv")
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [150]:
df.shape

(303, 14)

In [151]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       303 non-null    int64  
 1   sex       303 non-null    int64  
 2   cp        303 non-null    int64  
 3   trestbps  303 non-null    int64  
 4   chol      303 non-null    int64  
 5   fbs       303 non-null    int64  
 6   restecg   303 non-null    int64  
 7   thalach   303 non-null    int64  
 8   exang     303 non-null    int64  
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64  
 11  ca        303 non-null    int64  
 12  thal      303 non-null    int64  
 13  target    303 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 33.3 KB


In [152]:
df.describe()

age         sex          cp    trestbps        chol         fbs  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean    54.366337    0.683168    0.966997  131.623762  246.264026    0.148515   
std      9.082101    0.466011    1.032052   17.538143   51.830751    0.356198   
min     29.000000    0.000000    0.000000   94.000000  126.000000    0.000000   
25%     47.500000    0.000000    0.000000  120.000000  211.000000    0.000000   
50%     55.000000    1.000000    1.000000  130.000000  240.000000    0.000000   
75%     61.000000    1.000000    2.000000  140.000000  274.500000    0.000000   
max     77.000000    1.000000    3.000000  200.000000  564.000000    1.000000   

          restecg     thalach       exang     oldpeak       slope          ca  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean     0.528053  149.646865    0.326733    1.039604    1.399340    0.729373   
std      0.525860   22.905161    0.469794    1.161075    0.616226    1.022606   
min      0.000000   71.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000  133.500000    0.000000    0.000000    1.000000    0.000000   
50%      1.000000  153.000000    0.000000    0.800000    1.000000    0.000000   
75%      1.000000  166.000000    1.000000    1.600000    2.000000    1.000000   
max      2.000000  202.000000    1.000000    6.200000    2.000000    4.000000   

             thal      target  
count  303.000000  303.000000  
mean     2.313531    0.544554  
std      0.612277    0.498835  
min      0.000000    0.000000  
25%      2.000000    0.000000  
50%      2.000000    1.000000  
75%      3.000000    1.000000  
max      3.000000    1.000000

In [155]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [156]:
df.duplicated().sum()

1

In [157]:
df.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64